plugins {
    id 'com.android.application'
}

def getGitShortHash() {
    def hash = ""
    def proc = "git rev-parse --short HEAD".execute()
    proc.in.eachLine { line -> hash = line }
    proc.err.eachLine { line -> println line }
    proc.waitFor()
    return hash
}

android {
    namespace "com.xuanfeng.browser"
    compileSdk 34

    defaultConfig {
        applicationId "com.xuanfeng.browser"
        minSdk 23
        targetSdk 34
        versionCode 3
        versionName "3.1"
    }

    signingConfigs {
        release {
            storeFile rootProject.file('android-keystore/com.zhouyi.studio.keystore')
            storePassword 'Yao990815,'
            keyAlias 'com.zhouyi.studio'
            keyPassword 'Yao990815,'
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    applicationVariants.all { variant ->
        variant.outputs.all {
            def hash = getGitShortHash()
            outputFileName = "XFBrowser-${hash}-dev.apk"
        }
    }
}

dependencies {
 // CodeAssist does NOT support adding dependencies here,
 // try using the library manager instead
}
