plugins {
    id 'com.android.application'
}

import org.gradle.api.provider.Provider

android {
    namespace "com.xuanfeng.browser"
    compileSdk 34

    defaultConfig {
        applicationId "com.xuanfeng.browser"
        minSdk 23
        targetSdk 34
        versionCode 3
        versionName "3.1"
    }

    signingConfigs {
        release {
            storeFile rootProject.file('android-keystore/com.zhouyi.studio.keystore')
            storePassword 'Yao990815,'
            keyAlias 'com.zhouyi.studio'
            keyPassword 'Yao990815,'
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    applicationVariants.configureEach { variant ->
        variant.outputs.configureEach { output ->
            def gitHashProvider = providers.exec {
                commandLine("git", "rev-parse", "--short", "HEAD")
            }.standardOutput.asText.map { it.trim() }
            output.outputFileName = gitHashProvider.map { hash ->
                "XFBrowser-${hash}-dev.apk"
            }
        }
    }
}

dependencies {
 // CodeAssist does NOT support adding dependencies here,
 // try using the library manager instead
}
